---
- name: Install efm-langserver from AUR (CachyOS/Arch)
  command: paru -S --noconfirm --needed efm-langserver
  args:
    creates: /usr/bin/efm-langserver
  when: ansible_facts.os_family == "Archlinux"

- name: Install efm-langserver in Linux (Debian/Fedora)
  unarchive:
    src: https://github.com/mattn/efm-langserver/releases/download/v{{ efm_langserver_version }}/efm-langserver_v{{ efm_langserver_version }}_linux_amd64.tar.gz
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "efm-langserver_v{{ efm_langserver_version }}_linux_amd64/efm-langserver"
  when: ansible_facts.system == "Linux" and ansible_facts.os_family != "Archlinux"

- name: Install efm-langserver in macOS
  community.general.homebrew:
    name:
      - efm-langserver
    state: present
  when: ansible_facts.distribution == "MacOSX"
