---
- name: Install efm-langserver
  import_tasks: efm-langserver.yml

- name: Install shellcheck
  import_tasks: shellcheck.yml

- name: Install yamllint on macOS
  community.general.homebrew:
    name: yamllint
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install yamllint on Ubuntu
  ansible.builtin.apt:
    name: yamllint
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"

- name: Install yamllint on Fedora
  ansible.builtin.dnf:
    name: yamllint
    state: present
  become: true
  when: ansible_facts.distribution == "Fedora"

- name: Install luacheck on Debian/Ubuntu
  ansible.builtin.apt:
    name: luarocks
    state: present
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Install luacheck on Fedora/RHEL
  ansible.builtin.dnf:
    name: luarocks
    state: present
  become: true
  when: ansible_facts.os_family == "RedHat"

- name: Install luacheck on macOS
  community.general.homebrew:
    name: luarocks
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install luacheck via luarocks
  ansible.builtin.shell:
    cmd: luarocks install --local luacheck
  register: luarocks_install
  changed_when: "'is now installed' in luarocks_install.stdout"
  failed_when: luarocks_install.rc != 0 and 'already installed' not in luarocks_install.stderr

- name: Install linters and formatters with npm
  become: true
  loop:
    - eslint
    - prettier
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  environment:
    PATH: "{{ ansible_facts.env.HOME }}/.local/bin:{{ ansible_facts.env.HOME }}/.asdf/shims:{{ ansible_facts.env.PATH }}"

- name: Install stylua from GitHub releases
  unarchive:
    src: "https://github.com/JohnnyMorganz/StyLua/releases/download/v{{ stylua_version }}/stylua-{{ 'macos' if ansible_facts['os_family'] == 'Darwin' else 'linux' }}.zip"
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    mode: "u+x"
    remote_src: true
