- name: Install shellcheck in Fedora/RHEL
  become: true
  dnf:
    name:
      - ShellCheck
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install shellcheck in Debian/Ubuntu
  become: true
  apt:
    name:
      - shellcheck
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install shellcheck in macOS
  community.general.homebrew:
    name:
      - shellcheck
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install shellcheck in CachyOS/Arch
  become: true
  community.general.pacman:
    name: shellcheck
    state: present
  when: ansible_facts.os_family == "Archlinux"
