---
- name: Install zsh
  tags: minimal
  import_tasks: zsh.yml

- name: Install zsh-syntax-highlighting
  tags: minimal
  import_tasks: zsh-syntax-highlighting.yml

- name: Install zsh-autosuggestions
  tags: minimal
  import_tasks: zsh-autosuggestions.yml
