---
- name: Install zsh-syntax-highlighting in Ubuntu
  become: true
  apt:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install zsh-syntax-highlighting in Fedora
  become: true
  dnf:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_distribution == "Fedora"

- name: Install zsh-syntax-highlighting in macOS
  community.general.homebrew:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_distribution == "MacOSX"
