---
- name: Install zsh-autosuggestions in Ubuntu
  tags: minimal
  become: true
  apt:
    name: zsh-autosuggestions
    state: present
  when: ansible_os_family == "Debian"

- name: Install zsh-autosuggestions in Fedora
  tags: minimal
  become: true
  dnf:
    name: zsh-autosuggestions
    state: present
  when: ansible_os_family == "RedHat"

- name: Install zsh-autosuggestions in macOS
  community.general.homebrew:
    name: zsh-autosuggestions
    state: present
  when: ansible_distribution == "MacOSX"
