---
- name: Install zsh-syntax-highlighting in Ubuntu
  become: true
  apt:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_os_family == "Debian"

- name: Install zsh-syntax-highlighting in Fedora
  become: true
  dnf:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_os_family == "RedHat"

- name: Install zsh-syntax-highlighting in macOS
  community.general.homebrew:
    name: zsh-syntax-highlighting
    state: present
  when: ansible_distribution == "MacOSX"
