---
- name: Setup Flatpak and apps
  import_tasks: flatpak.yml

- name: Setup Fedora
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Setup Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install ulauncher
  import_tasks: ulauncher.yml

- name: Configure GNOME
  import_tasks: gnome.yml
