---
- name: Setup Flatpak and apps
  import_tasks: flatpak.yml

- name: Setup Fedora/RHEL
  import_tasks: fedora.yml
  when: ansible_facts.os_family == "RedHat"

- name: Setup Debian/Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts.os_family == "Debian"

- name: Install ulauncher
  import_tasks: ulauncher.yml

- name: Configure GNOME
  import_tasks: gnome.yml
