---
- name: Setup Flatpak and apps
  import_tasks: flatpak.yml

- name: Setup Fedora/RHEL
  import_tasks: fedora.yml
  when: ansible_facts.os_family == "RedHat"

- name: Setup Debian/Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts.os_family == "Debian"

- name: Setup CachyOS/Arch
  import_tasks: arch.yml
  when: ansible_facts.os_family == "Archlinux"

- name: Build and install Vicinae launcher
  import_tasks: vicinae.yml

- name: Configure GNOME
  import_tasks: gnome.yml
