---
- name: Add 1Password GPG key (Ubuntu)
  become: true
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /usr/share/keyrings/1password-archive-keyring.asc
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Add 1Password repository (Ubuntu)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present
  when: ansible_os_family == "Debian"

- name: Install 1Password (Ubuntu)
  become: true
  apt:
    name:
      - 1password
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Add 1Password GPG key (Fedora)
  become: true
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  when: ansible_os_family == "RedHat"

- name: Add 1Password repository (Fedora)
  become: true
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Repository
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  when: ansible_os_family == "RedHat"

- name: Install 1Password (Fedora)
  become: true
  dnf:
    name:
      - 1password
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure local applications directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/applications"
    state: directory
    mode: '0755'
  when: ansible_system == "Linux"

- name: Create 1Password silent startup .desktop file
  copy:
    dest: "{{ ansible_env.HOME }}/.local/share/applications/1password-silent.desktop"
    mode: '0644'
    content: |
      [Desktop Entry]
      Name=1Password (silent)
      Comment=Start 1Password silently in the background
      Exec=/usr/bin/1password --silent
      Terminal=false
      Type=Application
      Icon=1password
      Categories=Utility;Security;
      StartupNotify=false
  when: ansible_system == "Linux"
