- name: Install alacritty in Debian/Ubuntu
  become: true
  apt:
    name: alacritty
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install alacritty in Fedora
  become: true
  dnf:
    name: alacritty
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install alacritty in macOS
  community.general.homebrew:
    name: alacritty
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install alacritty in CachyOS/Arch
  become: true
  community.general.pacman:
    name: alacritty
    state: present
  when: ansible_facts.os_family == "Archlinux"
