- name: Install alacritty in Ubuntu
  become: true
  apt:
    name: alacritty
    state: present
  when: ansible_os_family == "Debian"

- name: Install alacritty in Fedora
  become: true
  dnf:
    name: alacritty
    state: present
  when: ansible_os_family == "RedHat"

- name: Install alacritty in macOS
  community.general.homebrew:
    name: alacritty
    state: present
  when: ansible_distribution == "MacOSX"
