---
- name: Install Blueman (Debian/Ubuntu)
  become: true
  apt:
    name: blueman
    state: present
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install Blueman (Fedora)
  become: true
  dnf:
    name: blueman
    state: present
  when: ansible_facts.distribution == "Fedora"

- name: Install Blueman (CachyOS/Arch)
  become: true
  community.general.pacman:
    name: blueman
    state: present
  when: ansible_facts.os_family == "Archlinux"
