- name: Tap cormacrelf/tap repository in macOS
  community.general.homebrew_tap:
    name: cormacrelf/tap
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install dark-notify in macOS
  community.general.homebrew:
    name: dark-notify
    state: present
  when: ansible_facts.distribution == "MacOSX"
