---
- name: Install Discord (macOS)
  community.general.homebrew_cask:
    name: discord
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install Discord (Debian/Ubuntu)
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
    method: user
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install Discord (Fedora)
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
    method: user
  when: ansible_facts.distribution == "Fedora"
