---
- name: Install fyi (Ubuntu/Debian)
  become: true
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install fyi (Fedora)
  become: true
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_facts.distribution == "Fedora"
