---
- name: Install fyi (Ubuntu/Debian)
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install fyi (Fedora)
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_distribution == "Fedora"
