---
- name: Install fyi (Debian/Ubuntu)
  become: true
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install fyi (Fedora)
  become: true
  ansible.builtin.package:
    name: fyi
    state: present
  when: ansible_facts.distribution == "Fedora"

- name: Install fyi from AUR (CachyOS/Arch)
  command: paru -S --noconfirm --needed fyi
  args:
    creates: /usr/bin/fyi
  when: ansible_facts.os_family == "Archlinux"
