---
- name: Install GIMP on Debian/Ubuntu
  become: true
  apt:
    name:
      - gimp
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install GIMP on Fedora/RHEL
  become: true
  dnf:
    name:
      - gimp
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install GIMP on macOS
  community.general.homebrew_cask:
    name: gimp
    state: present
  when: ansible_facts.distribution == "MacOSX"
