---
- name: Install GIMP on Debian/Ubuntu
  become: true
  apt:
    name:
      - gimp
    state: present
  when: ansible_os_family == "Debian"

- name: Install GIMP on Fedora/RHEL
  become: true
  dnf:
    name:
      - gimp
    state: present
  when: ansible_os_family == "RedHat"
