---
- name: Install Inkscape on Debian/Ubuntu
  become: true
  apt:
    name:
      - inkscape
    state: present
  when: ansible_os_family == "Debian"

- name: Install Inkscape on Fedora/RHEL
  become: true
  dnf:
    name:
      - inkscape
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Inkscape on macOS
  community.general.homebrew_cask:
    name: inkscape
    state: present
  when: ansible_distribution == "MacOSX"
