- name: Install kitty in Debian/Ubuntu
  become: true
  apt:
    name: kitty
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install kitty in Fedora
  become: true
  dnf:
    name: kitty
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install kitty in macOS
  community.general.homebrew:
    name: kitty
    state: present
  when: ansible_facts.distribution == "MacOSX"
