---
- name: Install Transmission (macOS)
  community.general.homebrew_cask:
    name: transmission
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install Transmission GTK (Debian/Ubuntu)
  become: true
  apt:
    name: transmission-gtk
    state: present
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install Transmission GTK (Fedora)
  become: true
  dnf:
    name: transmission-gtk
    state: present
  when: ansible_facts.distribution == "Fedora"
