---
- name: Install Transmission (macOS)
  community.general.homebrew_cask:
    name: transmission
    state: present
  when: ansible_distribution == "MacOSX"

# Fragments is a modern GNOME BitTorrent client (GTK4)
- name: Install Fragments BitTorrent client (Ubuntu/Debian)
  community.general.flatpak:
    name: de.haeckerfelix.Fragments
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install Fragments BitTorrent client (Fedora)
  community.general.flatpak:
    name: de.haeckerfelix.Fragments
    state: present
  when: ansible_distribution == "Fedora"
