---
- name: Install ueberzugpp on Ubuntu
  become: true
  apt:
    name: ueberzugpp
    state: present
  when: ansible_os_family == "Debian"

- name: Build and install ueberzugpp on Fedora
  import_tasks: ueberzugpp-fedora.yml
  when: ansible_os_family == "RedHat"
