---
- name: Install ueberzugpp on Ubuntu
  become: true
  apt:
    name: ueberzugpp
    state: present
  when: ansible_facts.distribution == "Ubuntu"

- name: Build and install ueberzugpp on Debian
  import_tasks: ueberzugpp-debian.yml
  when: ansible_facts.distribution == "Debian"

- name: Build and install ueberzugpp on Fedora
  import_tasks: ueberzugpp-fedora.yml
  when: ansible_facts.os_family == "RedHat"
