---
- name: Install WireGuard (macOS)
  community.general.homebrew:
    name:
      - wireguard-tools
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install WireGuard (CachyOS/Arch)
  become: true
  community.general.pacman:
    name:
      - wireguard-tools
    state: present
  when: ansible_facts.os_family == "Archlinux"
