- name: Install zathura in Debian/Ubuntu
  become: true
  apt:
    name:
      - zathura
      - zathura-pdf-poppler
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install zathura in Fedora
  become: true
  dnf:
    name:
      - zathura
      - zathura-pdf-poppler
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install zathura in CachyOS/Arch
  become: true
  community.general.pacman:
    name:
      - zathura
      - zathura-pdf-poppler
    state: present
  when: ansible_facts.os_family == "Archlinux"
