---
- name: Install fuzzel utility scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
    mode: '0755'
  loop:
    - fuzzel-wifi
    - fuzzel-clipboard
    - fuzzel-emoji
    - fuzzel-history
    - fuzzel-tldr
    - fuzzel-cheat
