---
- name: Ensure .local/src directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/src"
    state: directory
    mode: '0755'

- name: Setup Wayfire
  import_tasks: wayfire.yml

- name: Setup Waybar
  import_tasks: waybar.yml

- name: Setup Extra Tools (Avizo, Fuzzel, SwayNC, Rofi, etc)
  import_tasks: extras.yml

- name: Setup Display Manager (Ly)
  import_tasks: ly.yml
