---
- name: Setup Flatpak and apps
  import_tasks: flatpak.yml

- name: Setup Fedora
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Setup Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install 1Password
  import_tasks: 1password.yml

- name: Install Vivaldi browser
  import_tasks: vivaldi.yml

- name: Install ulauncher
  import_tasks: ulauncher.yml

- name: Install Arduino IDE
  import_tasks: arduino.yml

- name: Install ueberzugpp
  import_tasks: ueberzugpp.yml

- name: Configure GNOME
  import_tasks: gnome.yml
