---
- name: Add Mullvad GPG key (Ubuntu)
  become: true
  ansible.builtin.get_url:
    url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    dest: /usr/share/keyrings/mullvad-keyring.asc
    mode: '0644'
  when: ansible_distribution == "Ubuntu"

- name: Add Mullvad repository (Ubuntu)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=amd64] https://repository.mullvad.net/deb/stable {{ ansible_distribution_release }} main"
    filename: mullvad
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Mullvad VPN (Ubuntu)
  become: true
  apt:
    name:
      - mullvad-vpn
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Add Mullvad GPG key (Fedora)
  become: true
  ansible.builtin.rpm_key:
    key: https://repository.mullvad.net/rpm/mullvad-keyring.asc
    state: present
  when: ansible_distribution == "Fedora"

- name: Add Mullvad repository (Fedora)
  become: true
  ansible.builtin.yum_repository:
    name: mullvad
    description: Mullvad VPN Repository
    baseurl: https://repository.mullvad.net/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://repository.mullvad.net/rpm/mullvad-keyring.asc
  when: ansible_distribution == "Fedora"

- name: Install Mullvad VPN (Fedora)
  become: true
  dnf:
    name:
      - mullvad-vpn
    state: present
  when: ansible_distribution == "Fedora"
