---
- name: Install WireGuard (Ubuntu)
  become: true
  apt:
    name:
      - wireguard
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install WireGuard (Fedora)
  become: true
  dnf:
    name:
      - wireguard-tools
    state: present
  when: ansible_distribution == "Fedora"
