---
diffstatic_version: 0.53.0
git_delta_version: 0.14.0
git_absorb_version: "0.6.9"
editorconfig_checker_version: 3.2.0
cheat_version: 4.4.2
tealdeer_version: 1.8.1
zellij_version: 0.41.2
just_version: 1.38.0
procs_version: 0.14.10
vivid_version: 0.10.1
