---
diffstatic_version: 0.53.0
git_delta_version: 0.14.0
bat_version: 0.23.0
git_absorb_version: "0.6.9"
zoxide_version: 0.9.1
editorconfig_checker_version: 3.2.0
cheat_version: 4.4.2
tlrc_version: 1.9.3
eza_version: 0.20.14
