---
- name: Install Stow in Ubuntu
  become: true
  apt:
    name:
      - stow
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Stow in Fedora
  become: true
  dnf:
    name:
      - stow
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install Stow in macOS
  community.general.homebrew:
    name:
      - stow
    state: present
  when: ansible_facts.distribution == "MacOSX"
