---
- name: Install vim on Debian/Ubuntu
  tags: minimal
  become: true
  apt:
    name: vim-nox
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install vim on Fedora
  tags: minimal
  become: true
  dnf:
    name: vim-enhanced
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install vim on macOS
  community.general.homebrew:
    name: vim
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install vim on CachyOS/Arch
  tags: minimal
  become: true
  community.general.pacman:
    name: vim
    state: present
  when: ansible_facts.os_family == "Archlinux"
