---
- name: Install zsh in Ubuntu
  tags: minimal
  become: true
  apt:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install zsh in Fedora
  tags: minimal
  become: true
  dnf:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family == "RedHat"
