---
- name: Install zsh in Debian/Ubuntu
  tags: minimal
  become: true
  apt:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install zsh in Fedora
  tags: minimal
  become: true
  dnf:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install zsh in CachyOS/Arch
  tags: minimal
  become: true
  community.general.pacman:
    name:
      - zsh
    state: present
  when: ansible_facts.os_family == "Archlinux"
