---
- name: Add 1Password CLI GPG key (Ubuntu)
  become: true
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /usr/share/keyrings/1password-archive-keyring.asc
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Add 1Password CLI repository (Ubuntu)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present
  when: ansible_os_family == "Debian"

- name: Install 1Password CLI (Ubuntu)
  become: true
  apt:
    name:
      - 1password-cli
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Add 1Password CLI GPG key (Fedora)
  become: true
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  when: ansible_os_family == "RedHat"

- name: Add 1Password CLI repository (Fedora)
  become: true
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password CLI Repository
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  when: ansible_os_family == "RedHat"

- name: Install 1Password CLI (Fedora)
  become: true
  dnf:
    name:
      - 1password-cli
    state: present
  when: ansible_os_family == "RedHat"

- name: Install 1Password CLI (macOS)
  community.general.homebrew:
    name:
      - 1password-cli
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install 1Password desktop app (macOS)
  community.general.homebrew_cask:
    name:
      - 1password
    state: present
  when: ansible_distribution == "MacOSX"
