---
- name: Install 7zip on Ubuntu
  become: true
  apt:
    name: 7zip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install 7zip on Fedora
  become: true
  dnf:
    name: 7zip
    state: present
  when: ansible_distribution == "Fedora"

- name: Install 7zip on macOS
  community.general.homebrew:
    name: 7zip
    state: present
  when: ansible_distribution == "MacOSX"
