---
- name: Install 7zip on Ubuntu
  become: true
  apt:
    name:
      - 7zip
      - 7zip-standalone
    state: present
  when: ansible_os_family == "Debian"

- name: Install 7zip on Fedora
  become: true
  dnf:
    name:
      - 7zip
      - 7zip-standalone-all
    state: present
  when: ansible_os_family == "RedHat"

- name: Install 7zip on macOS
  community.general.homebrew:
    name: 7zip
    state: present
  when: ansible_distribution == "MacOSX"
