- name: Install aria2 in Debian/Ubuntu
  become: true
  apt:
    name: aria2
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install aria2 in Fedora
  become: true
  dnf:
    name:
      - aria2
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install aria2 in macOS
  community.general.homebrew:
    name:
      - aria2
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install aria2 in CachyOS/Arch
  become: true
  community.general.pacman:
    name: aria2
    state: present
  when: ansible_facts.os_family == "Archlinux"
