- name: Install bat in Ubuntu
  become: true
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-musl_{{ bat_version }}_amd64.deb
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: ansible_os_family == "Debian"

- name: Install bat in Fedora
  become: true
  dnf:
    name:
      - bat
    state: present
  when: ansible_os_family == "RedHat"

- name: Install bat in macOS
  community.general.homebrew:
    name:
      - bat
    state: present
  when: ansible_distribution == "MacOSX"
