---
- name: Install btop on Ubuntu
  become: true
  apt:
    name: btop
    state: present
  when: ansible_os_family == "Debian"

- name: Install btop on Fedora
  become: true
  dnf:
    name: btop
    state: present
  when: ansible_os_family == "RedHat"

- name: Install btop on macOS
  community.general.homebrew:
    name: btop
    state: present
  when: ansible_distribution == "MacOSX"
