---
- name: Install chafa in Ubuntu
  become: true
  apt:
    name: chafa
    state: present
  when: ansible_os_family == "Debian"

- name: Install chafa in Fedora
  become: true
  dnf:
    name: chafa
    state: present
  when: ansible_os_family == "RedHat"

- name: Install chafa in macOS
  community.general.homebrew:
    name: chafa
    state: present
  when: ansible_distribution == "MacOSX"
