- name: Install choose via cargo-binstall in Linux (non-Arch)
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y choose"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/choose"
  when: ansible_facts.os_family in ["Debian", "RedHat"]

- name: Install choose in macOS
  community.general.homebrew:
    name:
      - choose-rust
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install choose in CachyOS/Arch
  become: true
  community.general.pacman:
    name: choose
    state: present
  when: ansible_facts.os_family == "Archlinux"
