---
- name: Install difftastic in Linux (non-Arch)
  unarchive:
    src: https://github.com/Wilfred/difftastic/releases/download/{{ diffstatic_version }}/difft-{{ ansible_facts.architecture }}-unknown-linux-gnu.tar.gz
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "difft"
  when: ansible_facts.system == "Linux" and ansible_facts.os_family != "Archlinux"

- name: Install difftastic in macOS
  community.general.homebrew:
    name:
      - difftastic
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install difftastic in CachyOS/Arch
  become: true
  community.general.pacman:
    name: difftastic
    state: present
  when: ansible_facts.os_family == "Archlinux"
