---
- name: Install difftastic in Linux
  unarchive:
    src: https://github.com/Wilfred/difftastic/releases/download/{{ diffstatic_version }}/difft-x86_64-unknown-linux-gnu.tar.gz
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "difft"
  when: ansible_facts.system == "Linux"

- name: Install difftastic in macOS
  community.general.homebrew:
    name:
      - difftastic
    state: present
  when: ansible_facts.distribution == "MacOSX"
