---
- name: Add dotfiles-rpms DNF repository
  become: true
  get_url:
    url: https://nisrael.github.io/dotfiles-rpms/packages/dotfiles-rpms.repo
    dest: /etc/yum.repos.d/dotfiles-rpms.repo
    mode: "0644"
  when: ansible_facts.os_family == "RedHat"

- name: Import dotfiles-rpms GPG key
  become: true
  rpm_key:
    key: https://nisrael.github.io/dotfiles-rpms/packages/RPM-GPG-KEY-dotfiles-rpms
    state: present
  when: ansible_facts.os_family == "RedHat"
  ignore_errors: true
