- name: Install dust in Ubuntu
  become: true
  apt:
    deb: https://github.com/bootandy/dust/releases/download/v{{ dust_version }}/du-dust_{{ dust_version }}-1_amd64.deb
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: ansible_os_family == "Debian"

- name: Install dust in Fedora
  become: true
  dnf:
    name:
      - du-dust
    state: present
  when: ansible_os_family == "RedHat"

- name: Install dust in macOS
  community.general.homebrew:
    name:
      - dust
    state: present
  when: ansible_distribution == "MacOSX"
