- name: Install dust in Debian/Ubuntu
  become: true
  apt:
    name: du-dust
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install dust in Fedora
  become: true
  dnf:
    name:
      - du-dust
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install dust in macOS
  community.general.homebrew:
    name:
      - dust
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install dust in CachyOS/Arch
  become: true
  community.general.pacman:
    name: dust
    state: present
  when: ansible_facts.os_family == "Archlinux"
