- name: Install dutree via cargo-binstall in Linux
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y dutree"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/dutree"
  when: ansible_facts.os_family in ["Debian", "RedHat", "Archlinux"]

- name: Install dutree in macOS
  community.general.homebrew:
    name:
      - dutree
    state: present
  when: ansible_facts.distribution == "MacOSX"
