- name: Install Vicinae from AUR (CachyOS/Arch)
  command: paru -S --noconfirm --needed dutree
  args:
    creates: /usr/bin/dutree
  when: ansible_facts.os_family == "Archlinux"

- name: Install dutree in macOS
  community.general.homebrew:
    name:
      - dutree
    state: present
  when: ansible_facts.distribution == "MacOSX"
