---
- name: Install Elixir in Debian/Ubuntu
  become: true
  apt:
    name:
      - elixir
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Elixir in Fedora
  become: true
  dnf:
    name:
      - elixir
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install Elixir in macOS
  community.general.homebrew:
    name: elixir
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install Elixir in CachyOS/Arch
  become: true
  community.general.pacman:
    name: elixir
    state: present
  when: ansible_facts.os_family == "Archlinux"
