---
- name: Install eza on Debian/Ubuntu
  tags: minimal
  become: true
  apt:
    name: eza
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install eza on Fedora/Linux
  tags: minimal
  unarchive:
    src: "https://github.com/eza-community/eza/releases/download/v{{ eza_version }}/eza_{{ ansible_facts.architecture }}-unknown-linux-gnu.tar.gz"
    remote_src: true
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    mode: '0755'
  when: ansible_facts.os_family == "RedHat"

- name: Install eza on macOS
  community.general.homebrew:
    name: eza
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install eza on CachyOS/Arch
  tags: minimal
  become: true
  community.general.pacman:
    name: eza
    state: present
  when: ansible_facts.os_family == "Archlinux"
