---
- name: Install eza on Ubuntu
  become: true
  apt:
    name: eza
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install eza on Fedora/Linux
  unarchive:
    src: "https://github.com/eza-community/eza/releases/download/v{{ eza_version }}/eza_x86_64-unknown-linux-gnu.tar.gz"
    remote_src: true
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: '0755'
  when: ansible_distribution == "Fedora"

- name: Install eza on macOS
  community.general.homebrew:
    name: eza
    state: present
  when: ansible_distribution == "MacOSX"
