---
- name: Install git-delta in Ubuntu/Debian
  become: true
  apt:
    name: git-delta
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install bat in Fedora
  become: true
  dnf:
    name:
      - git-delta
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install bat in macOS
  community.general.homebrew:
    name:
      - git-delta
    state: present
  when: ansible_facts.distribution == "MacOSX"
