---
- name: Install git-delta in Ubuntu
  become: true
  apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/git-delta_{{ git_delta_version }}_amd64.deb"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: ansible_os_family == "Debian"

- name: Install bat in Fedora
  become: true
  dnf:
    name:
      - git-delta
    state: present
  when: ansible_os_family == "RedHat"

- name: Install bat in macOS
  community.general.homebrew:
    name:
      - git-delta
    state: present
  when: ansible_distribution == "MacOSX"
