---
- name: Install git-absorb in Linux (non-Arch)
  unarchive:
    src: "https://github.com/tummychow/git-absorb/releases/download/{{ git_absorb_version }}/git-absorb-{{ git_absorb_version }}-x86_64-unknown-linux-musl.tar.gz"
    remote_src: true
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    extra_opts:
      - "--strip-components=1"
      - "git-absorb-{{ git_absorb_version }}-x86_64-unknown-linux-musl/git-absorb"
  when: ansible_facts.system == "Linux" and ansible_facts.os_family != "Archlinux"

- name: Install git-absorb in macOS
  community.general.homebrew:
    name:
      - git-absorb
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install git-absorb in CachyOS/Arch
  become: true
  community.general.pacman:
    name: git-absorb
    state: present
  when: ansible_facts.os_family == "Archlinux"
