- name: Install glow in Debian/Ubuntu
  become: true
  apt:
    name: glow
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install glow in Fedora
  become: true
  dnf:
    name:
      - glow
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install glow in macOS
  community.general.homebrew:
    name:
      - glow
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install glow in CachyOS/Arch
  become: true
  community.general.pacman:
    name: glow
    state: present
  when: ansible_facts.os_family == "Archlinux"
