---
- name: Install Go in Debian/Ubuntu
  become: true
  apt:
    name:
      - golang
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Go in Fedora
  become: true
  dnf:
    name:
      - golang
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install Go in macOS
  community.general.homebrew:
    name:
      - go
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install Go in CachyOS/Arch
  become: true
  community.general.pacman:
    name: go
    state: present
  when: ansible_facts.os_family == "Archlinux"
