---
- name: Install Go in Ubuntu
  become: true
  apt:
    name:
      - golang
    state: present
  when: ansible_os_family == "Debian"

- name: Install Go in Fedora
  become: true
  dnf:
    name:
      - golang
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Go in macOS
  community.general.homebrew:
    name:
      - go
    state: present
  when: ansible_distribution == "MacOSX"
