- name: Install gping in Debian/Ubuntu
  become: true
  apt:
    name: gping
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install gping in Fedora
  become: true
  dnf:
    name:
      - gping
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install gping in macOS
  community.general.homebrew:
    name:
      - gping
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install gping in CachyOS/Arch
  become: true
  community.general.pacman:
    name: gping
    state: present
  when: ansible_facts.os_family == "Archlinux"
