- name: Install gron in Debian/Ubuntu
  become: true
  apt:
    name: gron
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install gron in Fedora
  unarchive:
    src: "https://github.com/tomnomnom/gron/releases/download/v0.7.1/gron-linux-{{ 'amd64' if ansible_facts.architecture == 'x86_64' else 'arm64' }}-0.7.1.tgz"
    remote_src: true
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    include:
      - gron
  when: ansible_facts.os_family == "RedHat"

- name: Install gron in macOS
  community.general.homebrew:
    name:
      - gron
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install gron in CachyOS/Arch
  become: true
  community.general.pacman:
    name: gron
    state: present
  when: ansible_facts.os_family == "Archlinux"
