- name: Install gron in Debian/Ubuntu
  become: true
  apt:
    name: gron
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install gron in Fedora
  become: true
  dnf:
    name:
      - gron
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install gron in macOS
  community.general.homebrew:
    name:
      - gron
    state: present
  when: ansible_facts.distribution == "MacOSX"
