- name: Install httpie in Debian/Ubuntu
  become: true
  apt:
    name: httpie
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install httpie in Fedora
  become: true
  dnf:
    name:
      - httpie
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install httpie in macOS
  community.general.homebrew:
    name:
      - httpie
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install httpie in CachyOS/Arch
  become: true
  community.general.pacman:
    name: httpie
    state: present
  when: ansible_facts.os_family == "Archlinux"
