---
- name: Install just on Debian/Ubuntu
  become: true
  apt:
    deb: https://github.com/casey/just/releases/download/{{ just_version }}/just_{{ just_version }}_amd64.deb
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  when: ansible_facts.os_family == "Debian"

- name: Install just on Fedora
  become: true
  dnf:
    name:
      - just
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install just on macOS
  community.general.homebrew:
    name:
      - just
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install just on CachyOS/Arch
  become: true
  community.general.pacman:
    name:
      - just
    state: present
  when: ansible_facts.os_family == "Archlinux"
