- name: Install kitty in Ubuntu
  become: true
  apt:
    name: kitty
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install kitty in Fedora
  become: true
  dnf:
    name: kitty
    state: present
  when: ansible_distribution == "Fedora"

- name: Install kitty in macOS
  community.general.homebrew:
    name: kitty
    state: present
  when: ansible_distribution == "MacOSX"
