---
- name: Create directory ~/.local/bin/
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

- name: Install CLI tools in Ubuntu
  become: true
  apt:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - unzip
      - xclip
      - moreutils
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install CLI tools in Fedora
  become: true
  dnf:
    name:
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - xclip
      - moreutils
      - gawk
    state: present
  when: ansible_distribution == "Fedora"

- name: Install CLI tools in macOS
  community.general.homebrew:
    name:
      - tig
      - tmux
      - ripgrep
      - fd
      - jq
      - htop
      - moreutils
      - gnu-tar
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install git-delta
  import_tasks: git-delta.yml

- name: Install difftastic
  import_tasks: difftastic.yml

- name: Install editorconfig-checker
  import_tasks: editorconfig.yml

- name: Install fzf
  command:
    cmd: ./install --bin
    chdir: "{{ ansible_env.HOME }}/.fzf"
    creates: "{{ ansible_env.HOME }}/.fzf/bin/fzf"

- name: Install git-absorb
  import_tasks: git-absorb.yml

- name: Install WSL utilities
  import_tasks: wsl.yml
  when: ansible_kernel is search("microsoft")

- name: Install tokei
  import_tasks: tokei.yml

- name: Install bat
  import_tasks: bat.yml

- name: Install 7zip
  import_tasks: 7zip.yml

- name: Install eza
  import_tasks: eza.yml

- name: Install btop
  import_tasks: btop.yml

- name: Install zellij
  import_tasks: zellij.yml

- name: Install yazi
  import_tasks: yazi.yml

- name: Install cheat
  import_tasks: cheat.yml

- name: Install tlrc
  import_tasks: tlrc.yml

- name: Install vim
  import_tasks: vim.yml

- name: Install Claude
  import_tasks: claude.yml

- name: Install zoxide
  import_tasks: zoxide.yml

- name: Install 1Password CLI
  import_tasks: 1password-cli.yml

- name: Install Vivaldi browser
  import_tasks: vivaldi.yml

- name: Install wezterm
  import_tasks: wezterm.yml

- name: Install kitty
  import_tasks: kitty.yml

- name: Install alacritty
  import_tasks: alacritty.yml

- name: Install Nerd Fonts
  import_tasks: nerd-fonts.yml

- name: Install CLI tools in npm
  loop:
    - strip-ansi-cli
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
