- name: Install map via cargo-binstall in Linux
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y map-cli"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/map"
  when: ansible_facts.os_family in ["Debian", "RedHat"]

- name: Install map in macOS
  community.general.homebrew:
    name:
      - map
    state: present
  when: ansible_facts.distribution == "MacOSX"
