- name: Clone map repository
  git:
    repo: https://github.com/soveran/map
    dest: "{{ ansible_facts.env.HOME }}/.local/src/map"
    version: master
    update: yes

- name: Build and install map
  shell: make install PREFIX="{{ ansible_facts.env.HOME }}/.local"
  args:
    chdir: "{{ ansible_facts.env.HOME }}/.local/src/map"
    creates: "{{ ansible_facts.env.HOME }}/.local/bin/map"
