---
- name: Install Maven in Ubuntu
  become: true
  apt:
    name:
      - maven
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Maven in Fedora
  become: true
  dnf:
    name:
      - maven
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install Maven in macOS
  community.general.homebrew:
    name:
      - maven
    state: present
  when: ansible_facts.distribution == "MacOSX"
