- name: Install mcfly in Debian/Ubuntu
  become: true
  apt:
    name: mcfly
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install mcfly in Fedora
  become: true
  dnf:
    name:
      - mcfly
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install mcfly in macOS
  community.general.homebrew:
    name:
      - mcfly
    state: present
  when: ansible_facts.distribution == "MacOSX"
