- name: Install mcfly via cargo-binstall in Linux (non-Arch)
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y mcfly"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/mcfly"
  when: ansible_facts.os_family in ["Debian", "RedHat"]

- name: Install mcfly in macOS
  community.general.homebrew:
    name:
      - mcfly
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install mcfly in CachyOS/Arch
  become: true
  community.general.pacman:
    name: mcfly
    state: present
  when: ansible_facts.os_family == "Archlinux"
