---
- name: Install meld on Debian/Ubuntu
  become: true
  apt:
    name: meld
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install meld on Fedora
  become: true
  dnf:
    name: meld
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install meld on macOS
  community.general.homebrew:
    name: meld
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install meld on CachyOS/Arch
  become: true
  community.general.pacman:
    name: meld
    state: present
  when: ansible_facts.os_family == "Archlinux"
