- name: Install mise in Ubuntu
  unarchive:
    src: https://github.com/jdx/mise/releases/download/v{{ mise_version }}/mise-v{{ mise_version }}-linux-x64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "--strip-components=2"
      - "mise/bin/mise"
  when: ansible_distribution == "Ubuntu"

- name: Install mise in Fedora
  unarchive:
    src: https://github.com/jdx/mise/releases/download/v{{ mise_version }}/mise-v{{ mise_version }}-linux-x64.tar.gz
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    extra_opts:
      - "--strip-components=2"
      - "mise/bin/mise"
  when: ansible_distribution == "Fedora"

- name: Install mise in macOS
  community.general.homebrew:
    name:
      - mise
    state: present
  when: ansible_distribution == "MacOSX"
