---
- name: Install navi in Debian/Ubuntu
  become: true
  apt:
    name: navi
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install navi in Fedora
  become: true
  dnf:
    name: navi
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install navi in macOS
  community.general.homebrew:
    name: navi
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install navi in CachyOS/Arch
  become: true
  community.general.pacman:
    name: navi
    state: present
  when: ansible_facts.os_family == "Archlinux"
