- name: Install nmon in Debian/Ubuntu
  become: true
  apt:
    name: nmon
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install nmon in Fedora
  become: true
  dnf:
    name:
      - nmon
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install nmon in macOS
  community.general.homebrew:
    name:
      - nmon
    state: present
  when: ansible_facts.distribution == "MacOSX"
