---
- name: Install OpenJDK 21 in Debian/Ubuntu
  become: true
  apt:
    name:
      - openjdk-21-jdk
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install OpenJDK 21 in Fedora
  become: true
  dnf:
    name:
      - java-21-openjdk-devel
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install OpenJDK 21 in macOS
  community.general.homebrew:
    name:
      - openjdk@21
    state: present
  when: ansible_facts.distribution == "MacOSX"
