---
- name: Install resvg in Debian/Ubuntu
  become: true
  apt:
    name: resvg
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install resvg in Fedora
  become: true
  dnf:
    name: resvg
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install resvg in macOS
  community.general.homebrew:
    name: resvg
    state: present
  when: ansible_facts.distribution == "MacOSX"
