---
- name: Install resvg in Ubuntu
  become: true
  apt:
    name: resvg
    state: present
  when: ansible_os_family == "Debian"

- name: Install resvg in Fedora
  become: true
  dnf:
    name: resvg
    state: present
  when: ansible_os_family == "RedHat"

- name: Install resvg in macOS
  community.general.homebrew:
    name: resvg
    state: present
  when: ansible_distribution == "MacOSX"
