- name: Install Ruby build dependencies in Debian/Ubuntu
  become: true
  apt:
    name:
      - build-essential
      - autoconf
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev
      - libffi-dev
      - libgmp-dev
      - rustc
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Ruby build dependencies in Fedora
  become: true
  dnf:
    name:
      - autoconf
      - gcc
      - rust
      - patch
      - make
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - gdbm-devel
      - ncurses-devel
      - perl-FindBin
      - zlib-ng-compat-devel
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install Ruby build dependencies in CachyOS/Arch
  become: true
  community.general.pacman:
    name:
      - autoconf
      - gcc
      - rust
      - patch
      - make
      - bzip2
      - openssl
      - libyaml
      - libffi
      - readline
      - gdbm
      - ncurses
    state: present
  when: ansible_facts.os_family == "Archlinux"
