- name: Install skim via cargo-binstall in Linux (non-Arch)
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y skim"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/sk"
  when: ansible_facts.os_family in ["Debian", "RedHat"]

- name: Install skim in macOS
  community.general.homebrew:
    name:
      - sk
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install skim in CachyOS/Arch
  become: true
  community.general.pacman:
    name: skim
    state: present
  when: ansible_facts.os_family == "Archlinux"
