---
- name: Install tig in Debian/Ubuntu
  become: true
  apt:
    name: tig
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install tig in Fedora
  become: true
  dnf:
    name: tig
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install tig in macOS
  community.general.homebrew:
    name: tig
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install tig in CachyOS/Arch
  become: true
  community.general.pacman:
    name: tig
    state: present
  when: ansible_facts.os_family == "Archlinux"
