---
- name: Install tig in Ubuntu
  become: true
  apt:
    name: tig
    state: present
  when: ansible_os_family == "Debian"

- name: Install tig in Fedora
  become: true
  dnf:
    name: tig
    state: present
  when: ansible_os_family == "RedHat"

- name: Install tig in macOS
  community.general.homebrew:
    name: tig
    state: present
  when: ansible_distribution == "MacOSX"
