- name: Install tokei in Fedora
  become: true
  dnf:
    name:
      - tokei
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install tokei in Debian/Ubuntu
  unarchive:
    src: https://github.com/XAMPPRocky/tokei/releases/download/v12.1.2/tokei-{{ ansible_facts.architecture }}-unknown-linux-gnu.tar.gz
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    remote_src: true
    include:
      - tokei
    extra_opts:
      - "-z"
  when: ansible_facts.os_family == "Debian"

- name: Install tokei in macOS
  community.general.homebrew:
    name:
     - tokei
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install tokei in CachyOS/Arch
  become: true
  community.general.pacman:
    name: tokei
    state: present
  when: ansible_facts.os_family == "Archlinux"
