- name: Install pipx on Fedora
  become: true
  ansible.builtin.dnf:
    name: pipx
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install vaping via pipx in Linux
  community.general.pipx:
    name: vaping
    state: present
  when: ansible_facts.os_family in ["Debian", "RedHat", "Archlinux"]

- name: Install vaping in macOS
  community.general.homebrew:
    name:
      - vaping
    state: present
  when: ansible_facts.distribution == "MacOSX"
