---
- name: Install vim on Ubuntu
  become: true
  apt:
    name: vim-nox
    state: present
  when: ansible_os_family == "Debian"

- name: Install vim on Fedora
  become: true
  dnf:
    name: vim-enhanced
    state: present
  when: ansible_os_family == "RedHat"

- name: Install vim on macOS
  community.general.homebrew:
    name: vim
    state: present
  when: ansible_distribution == "MacOSX"
