- name: Install vivid in Ubuntu
  become: true
  apt:
    deb: https://github.com/sharkdp/vivid/releases/download/v{{ vivid_version }}/vivid_{{ vivid_version }}_amd64.deb
  when: ansible_facts.distribution == "Ubuntu"

- name: Enable COPR repository for vivid on Fedora
  become: true
  community.general.copr:
    name: lihaohong/yazi 
    state: enabled
  when: ansible_facts.os_family == "RedHat"

- name: Install vivid in Fedora
  become: true
  dnf:
    name:
      - vivid
    state: present
  when: ansible_facts.distribution == "Fedora"

- name: Install vivid in macOS
  community.general.homebrew:
    name:
      - vivid
    state: present
  when: ansible_facts.distribution == "MacOSX"
