- name: Install vivid in Ubuntu
  become: true
  apt:
    deb: https://github.com/sharkdp/vivid/releases/download/v{{ vivid_version }}/vivid_{{ vivid_version }}_amd64.deb
  when: ansible_facts.distribution == "Ubuntu"

- name: Install vivid in Fedora
  command: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo install vivid@{{ vivid_version }}"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/vivid"
  environment:
    PATH: "{{ ansible_facts.env.HOME }}/.cargo/bin:{{ ansible_facts.env.PATH }}"
  when: ansible_facts.os_family == "RedHat"

- name: Install vivid in macOS
  community.general.homebrew:
    name:
      - vivid
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install vivid in CachyOS/Arch
  become: true
  community.general.pacman:
    name: vivid
    state: present
  when: ansible_facts.os_family == "Archlinux"
