---
- name: Install wl-clipboard in Debian/Ubuntu
  become: true
  apt:
    name: wl-clipboard
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install wl-clipboard in Fedora
  become: true
  dnf:
    name: wl-clipboard
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install wl-clipboard in macOS (not needed)
  debug:
    msg: "wl-clipboard not needed on macOS (Wayland-specific tool)"
  when: ansible_facts.distribution == "MacOSX"

- name: Install wl-clipboard in CachyOS/Arch
  become: true
  community.general.pacman:
    name: wl-clipboard
    state: present
  when: ansible_facts.os_family == "Archlinux"
