---
- name: Install xclip in Debian/Ubuntu
  become: true
  apt:
    name: xclip
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install xclip in Fedora
  become: true
  dnf:
    name: xclip
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install xclip in macOS (not needed, using pbcopy/pbpaste)
  debug:
    msg: "xclip not needed on macOS, using native pbcopy/pbpaste"
  when: ansible_facts.distribution == "MacOSX"
