- name: Install xmlstarlet in Debian/Ubuntu
  become: true
  apt:
    name: xmlstarlet
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install xmlstarlet in Fedora
  become: true
  dnf:
    name:
      - xmlstarlet
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install xmlstarlet in macOS
  community.general.homebrew:
    name:
      - xmlstarlet
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install xmlstarlet in CachyOS/Arch
  become: true
  community.general.pacman:
    name: xmlstarlet
    state: present
  when: ansible_facts.os_family == "Archlinux"
