- name: Install xsv in Linux (x86_64)
  unarchive:
    src: https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
    dest: "{{ ansible_facts.env.HOME }}/.local/bin"
    remote_src: true
    include:
      - xsv
  when: ansible_facts.system == "Linux" and ansible_facts.os_family != "Archlinux" and ansible_facts.architecture == "x86_64"

- name: Install xsv in Linux (aarch64)
  command: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo install xsv"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/xsv"
  environment:
    PATH: "{{ ansible_facts.env.HOME }}/.cargo/bin:{{ ansible_facts.env.PATH }}"
  when: ansible_facts.system == "Linux" and ansible_facts.os_family != "Archlinux" and ansible_facts.architecture == "aarch64"

- name: Install xsv in macOS
  community.general.homebrew:
    name:
      - xsv
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install xsv in CachyOS/Arch
  become: true
  community.general.pacman:
    name: xsv
    state: present
  when: ansible_facts.os_family == "Archlinux"
