---
# Debian/Ubuntu installation via griffo.io debian repository (added by dariogriffo-repo.yml)
- name: Install yazi on Debian/Ubuntu
  ansible.builtin.apt:
    name: yazi
    state: present
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Enable COPR repository for yazi on Fedora
  become: true
  community.general.copr:
    name: lihaohong/yazi
    state: enabled
  when: ansible_facts.os_family == "RedHat"

- name: Install yazi on Fedora
  become: true
  dnf:
    name: yazi
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install yazi on macOS
  community.general.homebrew:
    name: yazi
    state: present
  when: ansible_facts.distribution == "MacOSX"

- name: Install yazi on CachyOS/Arch
  become: true
  community.general.pacman:
    name: yazi
    state: present
  when: ansible_facts.os_family == "Archlinux"
