---
- name: Download zellij binary on Linux
  become: true
  unarchive:
    src: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-x86_64-unknown-linux-musl.tar.gz"
    remote_src: true
    dest: /usr/local/bin
    mode: '0755'
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Fedora"

- name: Install zellij on macOS
  community.general.homebrew:
    name: zellij
    state: present
  when: ansible_distribution == "MacOSX"
